name: renegade
version: '${project.version}'
main: org.hey.renegade.Renegade
api-version: '1.20'
commands:
  allow:
    description: Whitelist person ip.
    usage: /allow name ip
    permission: 'renegade.allow'
    permission-message: 'You do not have the necessary permission to run this command'
  deny:
    description: Blacklist person ip.
    usage: /deny name
    permission: 'renegade.deny'
    permission-message: 'You do not have the necessary permission to run this command'
  backup-now:
    description: Creates world backup.
    usage: /backup-now
    permission: 'renegade.backup'
    permission-message: 'You do not have the necessary permission to run this command'
  backup-interval:
    description: How often to backup the world.
    usage: /backup-interval
    permission: 'renegade.backup'
    permission-message: 'You do not have the necessary permission to run this command'